# Generated by Django 3.0.5 on 2020-07-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_id', models.CharField(max_length=50)),
                ('bed_curing_layer', models.IntegerField(blank=True, default=0)),
                ('bed_curing_time', models.IntegerField(blank=True, default=0)),
                ('curing_time', models.IntegerField(blank=True, default=0)),
                ('layer_delay', models.IntegerField(blank=True, default=0)),
                ('z_hop_height', models.IntegerField(blank=True, default=0)),
                ('max_speed', models.IntegerField(blank=True, default=0)),
                ('init_speed', models.IntegerField(blank=True, default=0)),
                ('up_accel_speed', models.IntegerField(blank=True, default=0)),
                ('up_decel_speed', models.IntegerField(blank=True, default=0)),
                ('down_accel_speed', models.IntegerField(blank=True, default=0)),
                ('down_decel_speed', models.IntegerField(blank=True, default=0)),
                ('contraction_ratio', models.FloatField(blank=True, default=0)),
                ('led_offset', models.FloatField(blank=True, default=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
