# Generated by Django 3.0.5 on 2020-07-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='M_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
