# Generated by Django 3.0.8 on 2020-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resin', '0002_auto_20200701_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='M_id',
            field=models.CharField(max_length=50),
        ),
    ]
