# Generated by Django 3.0.7 on 2020-08-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productserial_created_date'),
        ('resin', '0003_auto_20200723_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='M_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='material',
            name='bed_curing_layer',
        ),
        migrations.RemoveField(
            model_name='material',
            name='bed_curing_time',
        ),
        migrations.RemoveField(
            model_name='material',
            name='contraction_ratio',
        ),
        migrations.RemoveField(
            model_name='material',
            name='curing_time',
        ),
        migrations.RemoveField(
            model_name='material',
            name='down_accel_speed',
        ),
        migrations.RemoveField(
            model_name='material',
            name='down_decel_speed',
        ),
        migrations.RemoveField(
            model_name='material',
            name='init_speed',
        ),
        migrations.RemoveField(
            model_name='material',
            name='layer_delay',
        ),
        migrations.RemoveField(
            model_name='material',
            name='led_offset',
        ),
        migrations.RemoveField(
            model_name='material',
            name='max_speed',
        ),
        migrations.RemoveField(
            model_name='material',
            name='up_accel_speed',
        ),
        migrations.RemoveField(
            model_name='material',
            name='up_decel_speed',
        ),
        migrations.RemoveField(
            model_name='material',
            name='z_hop_height',
        ),
        migrations.AddField(
            model_name='material',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.CreateModel(
            name='PrintSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_height', models.FloatField(blank=True, default=0)),
                ('bed_curing_layer', models.IntegerField(blank=True, default=0)),
                ('bed_curing_time', models.IntegerField(blank=True, default=0)),
                ('curing_time', models.IntegerField(blank=True, default=0)),
                ('layer_delay', models.IntegerField(blank=True, default=0)),
                ('z_hop_height', models.IntegerField(blank=True, default=0)),
                ('max_speed', models.IntegerField(blank=True, default=0)),
                ('init_speed', models.IntegerField(blank=True, default=0)),
                ('up_accel_speed', models.IntegerField(blank=True, default=0)),
                ('up_decel_speed', models.IntegerField(blank=True, default=0)),
                ('down_accel_speed', models.IntegerField(blank=True, default=0)),
                ('down_decel_speed', models.IntegerField(blank=True, default=0)),
                ('contraction_ratio', models.FloatField(blank=True, default=0)),
                ('led_offset', models.FloatField(blank=True, default=100)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resin.Material')),
            ],
            options={
                'unique_together': {('layer_height', 'material')},
            },
        ),
    ]
